### ISSUE TITLE
 It doesn't seem to support GoPro13？

### ISSUE THREAD

**Issue by chenxun0306** [juanmcasillas/gopro2gpx#47]
I confirm that I can correctly locate the trajectory in Quik. It doesn't seem to support GoPro13？
![屏幕截图 2024-09-26 165414](https://github.com/user-attachments/assets/2166fee0-c45c-4c69-b80a-28a7f58541a6)

**Comment by ChristopheVeber** [comment]
I can confirm from my end that gopro2gpx does not parse mp4 files created from GoPro HERO 13 black:
[GoPro13data.zip](https://github.com/user-attachments/files/18364154/GoPro13data.zip) contains the gpmd stream of a video file. I get the following error messages
```
> gopro2gpx -b -vv GoPro13data.bin GoPro13data
Reading binary file GoPro13data.bin
Creating output file for binary data: GoPro13data.00.bin
Warning. fourCC Label 'CSCM' not found. Please summit a issue to: https://github.com/juanmcasillas/gopro2gpx/issues/new
Warning. fourCC Label 'LOGS' not found. Please summit a issue to: https://github.com/juanmcasillas/gopro2gpx/issues/new
Warning. fourCC Label 'LOGS' not found. Please summit a issue to: https://github.com/juanmcasillas/gopro2gpx/issues/new
Warning. fourCC Label 'PRJT' not found. Please summit a issue to: https://github.com/juanmcasillas/gopro2gpx/issues/new
...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\pipenvs\ppc\Scripts\gopro2gpx.exe\__main__.py", line 7, in <module>
  File "C:\pipenvs\ppc\Lib\site-packages\gopro2gpx\gopro2gpx.py", line 273, in main
    main_core(args)
  File "C:\pipenvs\ppc\Lib\site-packages\gopro2gpx\gopro2gpx.py", line 251, in main_core
    data += gpmf.parseStream(raw_data, config.verbose)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pipenvs\ppc\Lib\site-packages\gopro2gpx\gpmf.py", line 75, in parseStream
    klv = KLVData(data,offset)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\pipenvs\ppc\Lib\site-packages\gopro2gpx\klvdata.py", line 25, in __init__
    self.fourCC = self.fourCC.decode()
                  ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 0: invalid continuation byte
```
[errormessage.txt](https://github.com/user-attachments/files/18364244/errormessage.txt)

**Comment by juanmcasillas** [comment]
Hello,

this week I'll try to fix the code to work with gopro13 hero black. Thank you very much for providing me an example to work with. I'll keep you informed.

Regards,

**Comment by juanmcasillas** [comment]
Hello.

I upload a new version that works with the GoPro13. Could you test it ? I get a track in canada, it's right ?

Thanks in advance,

**Comment by ChristopheVeber** [comment]
> Hello.
> 
> I upload a new version that works with the GoPro13. Could you test it ? I get a track in canada, it's right ?
> 
> Thanks in advance,

That's right.
